Updating Translation + BugFix
this update contains 3 main features:

- Updating the translation to stay update to the master project

- Bug Fix in controller/Users.php:
Error: When an user saves it's own setting the language column will be
saved as black on db. This was caused by a form rule in line 807.
Corrected with proper naming 'language'.

- Updated the region/sideba.php and region/admin_sidebar.php to respect
the new "general templating" for dinamic language translation.